apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: profiles.kubeflow.org
spec:
  group: kubeflow.org
  version: v1
  names:
    kind: Profile
    plural: profiles
  scope: Namespaced
